name: Test API

on:
  workflow_call:
    inputs:
      context_path:
        required: true
        type: string
permissions:
  contents: read

jobs:
  test:
    name: Find csproj
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Find all csproj
        run: |

          # define empty arrays for service names and versions
          declare -a service_names
          declare -a versions

          # loop through each .csproj file in the current directory and its subdirectories
          for file in $(find ${{ inputs.context_path }} -name "*.csproj")
          do
              # loop through each matching line in the current file
              while IFS= read -r line
              do
                  # use regex to parse the service name and version
                  if [[ $line =~ Bse\.(.*)\.Api\.Server\"\ Version=\"(.*)\" ]] ; then
                      # append to the arrays
                      service_names+=(${BASH_REMATCH[1]})
                      versions+=(${BASH_REMATCH[2]})
                  fi
              done < <(grep -o '<PackageReference Include="Bse.*Api.Server" Version=".*" />' $file)
          done

          # print the arrays
          echo "Service Names: ${service_names[@]}"
          echo "Versions: ${versions[@]}"
