name: Build & Push Docker Image To AWS ECR

on:
  workflow_call:
    inputs:
      aws_ci_region:
        type: string
        default: "us-east-1"
      service_name:
        required: true
        type: string
      context_path:
        required: true
        type: string
      aws_ci_account:
        type: string
        default: "479886561928"
permissions:
  contents: read

env:
  repository: dkr.ecr.${{ inputs.aws_ci_region }}.amazonaws.com/${{ inputs.service_name }}

jobs:
  build-push:
    runs-on: ubuntu-latest
    name: Service build and push
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials "DEV"
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
          aws-region: ${{ inputs.aws_ci_region }}

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v1
      - name: Registry check/creation
        run: |
          aws ecr describe-repositories --repository-names ${{ inputs.service_name }} \
          || aws ecr create-repository --repository-name ${{ inputs.service_name }}

      - name: Lifecycle policy check/creation
        run: |
          aws ecr get-lifecycle-policy --repository-name ${{ inputs.service_name }} \
          || aws ecr put-lifecycle-policy --repository-name ${{ inputs.service_name }} \
          --lifecycle-policy-text "file://./.github/templates/ecr-policy.json"

      - name: Login to ECR
        uses: docker/login-action@v2.0.0
        with:
          registry: ${{ inputs.aws_ci_account }}.${{ env.repository }}
          username: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
          ecr: true
          logout: true

      - name: Replace branch name bad chars
        id: branch_name
        run: |
          if [ ${{ github.event_name }} == "pull_request" ]; then
            name=$( echo '${{ github.head_ref }}' | tr '/' '-' )
            echo "::set-output name=branch_name::$name"
          else
            name=$( echo '${{ github.ref_name }}' | tr '/' '-' )
            echo "::set-output name=branch_name::$name"
          fi

      - name: Docker build and push
        uses: docker/build-push-action@v3.2.0
        with:
          context: ${{ inputs.context_path }}
          push: ${{ github.event_name == 'push' }}  # Only push image to registry on "push" events.
          tags: 
            ${{ inputs.aws_ci_account }}.${{ env.repository }}:${{ github.run_id }},
            ${{ inputs.aws_ci_account }}.${{ env.repository }}:${{ steps.branch_name.outputs.branch_name }},
            ${{ inputs.aws_ci_account }}.${{ env.repository }}:${{ github.sha }}
          file: ${{ inputs.dockerfile_path }} 
          build-args: |
            "BSII_NUGET_URL=${{ secrets.BSII_NUGET_URL }}"
            "BSII_NUGET_USER=${{ secrets.BSII_NUGET_USER }}"
            "BSII_NUGET_PASSWORD=${{ secrets.BSII_NUGET_PASSWORD }}"
