name: Configure AWS credentials

inputs:
  env:
    type: string
    required: true
  region:
    type: string
    required: true

runs:
  using: "composite"
  steps:
  - name: Configure AWS Credentials "DEV"
    if: inputs.env == 'dev' || inputs.env == 'test'
    uses: aws-actions/configure-aws-credentials@v1-node16
    with:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
      aws-region: ${{ inputs.region }}

  - name: Configure AWS Credentials "QA"
    if: inputs.env == 'qa'
    uses: aws-actions/configure-aws-credentials@v1-node16
    with:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_QA }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_QA }}
      aws-region: ${{ inputs.region }}

  - name: Configure AWS Credentials "PROD"
    if: inputs.env == 'prod' || inputs.env == 'staging'
    uses: aws-actions/configure-aws-credentials@v1-node16
    with:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}
      aws-region: ${{ inputs.region }}    