name: CI service

on:
  workflow_call:
    inputs:
      dockerfile_path:
        required: true
        type: string
      service_name:
        required: true
        type: string
      context_path:
        required: true
        type: string
      aws_ci_region:
        type: string
        default: "us-east-1"
      ecr_registry:
        type: string
        default: "479886561928.dkr.ecr.us-east-1.amazonaws.com"
      enable-ecr:
        required: false
        type: boolean
        default: true

permissions:
  contents: read

jobs:
  build-push-ecr:
    if: ${{ inputs.enable-ecr }}
    runs-on: ubuntu-latest
    name: Service build and push to AWS ECR
    steps:
      - name: List environment variables 
        run: env

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
          aws-region: ${{ inputs.aws_ci_region }}

      - name: Login to ECR
        uses: docker/login-action@v2.0.0
        with:
          registry: ${{ inputs.ecr_registry }}/${{ inputs.service_name }}
          username: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
          ecr: true
          logout: true
      
      - name: Docker build and push
        run: |
               short_sha=$(git rev-parse --short "$GITHUB_SHA")
               echo "${{ inputs.ecr_registry }}/${{ inputs.service_name }}:${{ github.ref_name }}-$short_sha"

               docker buildx build \
               -o type=registry \
               -t "${{ inputs.ecr_registry }}/${{ inputs.service_name }}:${{ github.ref_name }}-$short_sha" \
               -f ${{ inputs.dockerfile_path }} \
               ${{ inputs.context_path }} \

      - name: Docker build and push
        run: |
               short_sha=$(git rev-parse --short "$GITHUB_SHA")
               docker buildx build \
               -o type=registry \
               -t ${{ env.ecr-repo-provider }}:${{ github.ref_name }}-$short_sha  \
               -f SOW2/SoW2/Provider/Dockerfile \
               SOW2/SoW2