name: CI service

on:
  workflow_call:
    inputs:
      context_path:
        required: true
        type: string
      enable-sonar:
        required: false
        type: boolean
      solution_file:
        required: false
        type: string

jobs:
  nx-ci:
    uses: ./.github/workflows/nx-ci.yaml
    secrets: inherit
    with:
      context_path: ${{ inputs.context_path }}

  sonar:
    if: ${{ inputs.enable-sonar }}
    uses: ./.github/workflows/sonar-sast.yaml
    needs: nx-ci
    secrets: inherit
    with:
      context_path: ${{ inputs.context_path }}
      solution_file: ${{ inputs.solution_file }}
