name: CI service

on:
  workflow_call:
    inputs:
      context_path:
        required: true
        type: string



jobs:
  nx-ci:
    uses: ./.github/workflows/nx-ci.yaml
    secrets:  inherit
    with:
      context_path: ${{ inputs.context_path }}

  sonar:
    if: ${{ inputs.enable-sonar }}
    uses: ./.github/workflows/sonar-sast-client.yaml
    needs: nx-ci
    secrets:  inherit
    with:
      context_path: ${{ inputs.context_path }}
