name: CI client

on:
  workflow_call:
    inputs:
      dockerfile_path:
        required: true
        type: string
      service_name:
        required: true
        type: string
      context_path:
        required: true
        type: string
      environment:
        type: string
        default: "479886561928"
        description: Default dev account

jobs:
  # Client, not dockerized
  test:
    name: Client unit tests
    runs-on: ubuntu-latest
    # continue-on-error needs to be deleted once there are real tests
    # continue-on-error: true
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.4.1
        with:
          node-version: 14

      - name: Install dev dependencies/chrome
        working-directory: ${{ inputs.context_path }}
        run: |
             npm install
             npm install -g @angular/cli@13.3.4
             wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
             sudo dpkg -i google-chrome-stable_current_amd64.deb

      - name: Test client
        working-directory: ${{ inputs.context_path }}
        run: ng test --browsers ChromeHeadless --watch=false


  build:
    runs-on: ubuntu-latest
    name: Client build and upload
    environment: ${{ inputs.environment }}
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}   
      AWS_DEFAULT_REGION: ${{ secrets.AWS_CI_REGION }}       
    needs: test
    permissions:
      contents: read
    steps:  
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.4.1
        with:
          node-version: 14

      - name: Install dependencies
        working-directory: ${{ inputs.context_path }}
        run: |
             npm install
             npm install -g @angular/cli@13.3.4

      - name: Build
        working-directory: ${{ inputs.context_path }}
        run: ng build

      - name: Replace branch name bad chars
        id: branch_name
        run: |
             if [ ${{ github.event_name }} == "pull_request" ]; then
               name=$( echo '${{ github.head_ref }}' | tr '/' '-' )
               echo "::set-output name=branch_name::$name"
             else
               name=$( echo '${{ github.ref_name }}' | tr '/' '-' )
               echo "::set-output name=branch_name::$name"
             fi

      # This step publishes the client artifact to an S3 bucket if triggered by "push" event, it checks if the bucket exists and creates it if not and attaches a lifecycle policy.
      # If triggered by the "dev" branch, the artkfact will be uploaded to "dev" folder, otherwise to "temp" folder.
      - name: Publish client artifact to S3 bucket
        if: ${{ github.event_name == 'push' }} 
        run: |
              cd ${{ inputs.context_path }}
              zip -r ${{ github.run_number }}-${{ steps.branch_name.outputs.branch_name }}.zip /dist
              
              aws s3api get-bucket-versioning --bucket s3-client-dev-${{ secrets.AWS_CI_REGION }} 1>/dev/null || \
              aws s3api create-bucket --acl private --bucket s3-client-dev-${{ secrets.AWS_CI_REGION }} && \
              aws s3api put-bucket-versioning --bucket s3-client-dev-${{ secrets.AWS_CI_REGION }} --versioning-configuration Status=Enabled && \
              aws s3api put-bucket-lifecycle-configuration --bucket s3-client-dev-${{ secrets.AWS_CI_REGION }} \
              --lifecycle-configuration  file://./.github/templates/client-lifecycle-policy.json

              if [ ${{ steps.branch_name.outputs.branch_name }} != 'dev' ]; then
                aws s3api put-object \
                --acl private \
                --bucket s3-client-dev-${{ secrets.AWS_CI_REGION }} \
                --body ${{ github.run_number }}-${{ steps.branch_name.outputs.branch_name }}.zip \
                --key temp/${{ github.run_number }}-${{ steps.branch_name.outputs.branch_name }}.zip
              else
                aws s3api put-object \
                --acl private \
                --bucket s3-client-dev-${{ secrets.AWS_CI_REGION }} \
                --body ${{ github.run_number }}-${{ steps.branch_name.outputs.branch_name }}.zip \
                --key dev/${{ github.run_number }}-${{ steps.branch_name.outputs.branch_name }}.zip
              fi
