name: CI Python

on:
  workflow_call:
    inputs:
      python-path:
        required: false
        type: string

  workflow_dispatch:
    inputs:
      test:
        description: "test"
        required: false
        default: "test"
        type: string

jobs:
  test:
    uses: ./.github/workflows/python-unit-test.yaml
    secrets: inherit
    with:
      python_path: ${{ inputs.python_path }}
