name: CI Python

on:
  workflow_call:
    inputs:
      unit_path:
        required: false
        type: string
      python_version:
        required: false
        type: string
        default: "3.9"

  workflow_dispatch:
    inputs:
      test:
        description: "test"
        required: false
        default: "test"
        type: string

jobs:
  test:
    uses: ./.github/workflows/python-unit-test.yaml
    secrets: inherit
    with:
      unit_path: ${{ inputs.unit_path }}
      python_version: ${{ inputs.python-version }}
