name: CI service

on:
  workflow_call:
    inputs:
      aws_ci_region:
        type: string
        default: "us-east-1"
      aws_ci_account:
        type: string
        default: "479886561928"
      projects_args:
        default: "[]"
        required: true
        type: string

jobs:
  ci-service:
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        array:  ${{ fromJson(inputs.projects_args) }}
    uses: ./.github/workflows/ci-service.yaml
    secrets: inherit
    name: CI for ${{ matrix.service_name }} 
    with:
        context_path: ${{ matrix.array.context_path }}
        solution_file: ${{ matrix.array.solution_file }}
        dockerfile_path: ${{ matrix.array.dockerfile_path }}
        service_name: ${{ matrix.array.service_name }}
