name: CI service

on:
  workflow_call:
    inputs:
      solution_file:
        required: true
        type: string
      dockerfile_path:
        required: true
        type: string
      build-args:
        type: string
        description: "List of build-time variables"
        required: false
      service_name:
        required: true
        type: string
      context_path:
        required: true
        type: string
      aws_ci_region:
        type: string
        default: "us-east-1"
      aws_ci_account:
        type: string
        default: "479886561928"
      enable-snyk:
        required: false
        type: boolean
        default: true
      enable-resharper:
        required: false
        type: boolean
        default: true
      enable-ecr:
        required: false
        type: boolean
        default: true
      enable-jfrog:
        required: false
        type: boolean
        default: false
      projects:
        default: "[]"
        required: true
        type: string

jobs:
  ci-service:
    name: Ci Dotnet Service
    runs-on: ubuntu-latest    
    environment: ${{ inputs.environment }}
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(inputs.projects_args) }}
    steps:
    - uses: ./.github/workflows/ci-service.yaml
      with:
        context_path: ${{ matrix.context_path }}
        solution_file: ${{ matrix.solution_file }}
        dockerfile_path: ${{ matrix.dockerfile_path }}
        build-args: ${{ matrix.build-args }}