name: CI service

on:
  workflow_call:
    inputs:
      solution_file:
        required: true
        type: string
      dockerfile_path:
        required: true
        type: string
      build-args:
        type: string
        description: "List of build-time variables"
        required: false
      service_name:
        required: true
        type: string
      context_path:
        required: true
        type: string
      enable_api_tests:
        required: false
        type: string
      aws_ci_region:
        type: string
        default: "us-east-1"
      aws_ci_account:
        type: string
        default: "479886561928"
      enable-test:
        required: false
        type: boolean
        default: true
      enable-resharper:
        required: false
        type: boolean
        default: true
      enable-sonarqube:
        required: false
        type: boolean
        default: true
      enable-ecr:
        required: false
        type: boolean
        default: false
        
    outputs:
      run_id:
        value: ${{ jobs.build-push-ecr.outputs.run_id }}

permissions:
  contents: read

jobs:
  # test:
  #   if: ${{ inputs.enable-test }}
  #   uses: ./.github/workflows/dotnet-build-test.yaml
  #   secrets: inherit
  #   with:
  #     context_path: ${{ inputs.context_path }}

  # api-test:
  #   if: ${{ inputs.enable_api_tests }}
  #   uses: ./.github/workflows/api-test.yaml
  #   secrets: inherit
  #   with:
  #     context_path: ${{ inputs.context_path }}

  # resharper:
  #   if: ${{ inputs.enable-resharper }}
  #   uses: ./.github/workflows/resharper.yaml
  #   secrets: inherit
  #   with:
  #     solution_file: ${{ inputs.solution_file }}
  #     context_path: ${{ inputs.context_path }}

  # sonarqube:
  #   if: ${{ inputs.enable-sonarqube }}
  #   uses: ./.github/workflows/sonar-sast.yaml
  #   secrets: inherit
  #   with:
  #     context_path: ${{ inputs.context_path }}
  #     solution_file: ${{ inputs.solution_file }}

  build-push-ecr:
    # if: (( inputs.enable-ecr && inputs.enable-test == false && always() ) || ( needs.test.result == 'success' && inputs.enable-ecr ))
    uses: ./.github/workflows/build-and-push-ecr.yaml
    secrets: inherit
    # needs: test
    with:
      context_path: ${{ inputs.context_path }}
      aws_ci_region: ${{ inputs.aws_ci_region }}
      aws_ci_account: ${{ inputs.aws_ci_account }}
      service_name: ${{ inputs.service_name }}
      dockerfile_path: ${{ inputs.dockerfile_path }}

