name: CI service

on:
  workflow_call:
    inputs:
      aws_ci_region:
        type: string
        default: "us-east-1"
      aws_ci_account:
        type: string
        default: "479886561928"
      projects_args:
        default: "[]"
        required: true
        type: string
      enable-test:
        required: false
        type: boolean
        default: true
      enable-resharper:
        required: false
        type: boolean
        default: false
      enable-ecr:
        required: false
        type: boolean
        default: true
      enable-snyk:
        required: false
        type: boolean
        default: false
      enable-sonarqube:
        required: false
        type: boolean
        default: true
      enable-polaris:
        required: false
        type: boolean
        default: true
      enable-coverity:
        required: false
        type: boolean
        default: true
    outputs:
      services:
        description: "The services to build"
        value: ${{ jobs.read-json.outputs.services }}
      run_id:
        value: ${{ jobs.ci-service.outputs.run_id }}

jobs:
  read-json:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
      - id: services
        run: |
          content=`cat ${{inputs.projects_args}}`
          echo "services<<EOF" >> $GITHUB_OUTPUT
          echo "$content" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          echo $content
    outputs:
      services: ${{ steps.services.outputs.services }}

  ci-service:
    needs: read-json
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        array: ${{ fromJson(needs.read-json.outputs.services) }}
    uses: ./.github/workflows/ci-service.yaml
    secrets: inherit
    name: CI for ${{ matrix.array.service_name }}
    with:
      context_path: ${{ matrix.array.context_path }}
      solution_file: ${{ matrix.array.solution_file }}
      dockerfile_path: ${{ matrix.array.dockerfile_path }}
      service_name: ${{ matrix.array.service_name }}
      enable-test: ${{ inputs.enable-test }}
      enable-ecr: ${{ inputs.enable-ecr }}
      enable-resharper: ${{ inputs.enable-resharper }}
      enable-snyk: ${{ inputs.enable-snyk }}
      enable-sonarqube: ${{ inputs.enable-sonarqube }}
      enable-polaris: ${{inputs.enable-polaris}}
      enable-coverity: ${{inputs.enable-coverity}}