name: delete-airflow

on:
  workflow_call:

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

env:
  aws_region: us-east-1

jobs:
  delete_airflow:
    if: github.event.ref_type == 'branch'
    runs-on: ubuntu-latest
    name: delete airflow
    steps:
      - name: List environment variables
        run: env

      - name: Configure AWS credentials "DEV"
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ARN_ROLE_OIDC_ADMINISTRATOR_DEV }}
          aws-region: ${{ env.aws_region }}

      - name: Checkout argocd
        uses: actions/checkout@v3
        with:
          repository: brightsource-il/argocd
          token: ${{ secrets.REPO_ACCESS_ARGOCD }}

      - name: helm uninstall airflow
        run: |
          aws eks --region ${{ env.aws_region }} update-kubeconfig --name eks-dev-${{ env.aws_region }}

          branch_without_slashes=$(echo "${{ github.event.ref }}" | sed 's/\//-/g')
          namespace="airflow-${{ github.event.repository.name }}-$branch_without_slashes"

          helm uninstall airflow --namespace $namespace

          if kubectl get namespace airflow-${{ github.event.repository.name }}-$branch_without_slashes &> /dev/null; 
          then 
            kubectl delete namespace airflow-${{ github.event.repository.name }}-$branch_without_slashes; 
          fi
