name: Build & Test a Dotnet Project

on:
  workflow_call:
    inputs:
      context_path:
        required: true
        type: string
permissions:
  contents: read

jobs:
  test:
    name: Service unit tests
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: |
          dotnet nuget add source ${{ secrets.BSII_NUGET_URL }} -n ArtifactoryV2   -u ${{ secrets.BSII_NUGET_USER }} -p ${{ secrets.BSII_NUGET_PASSWORD }} --store-password-in-clear-text
          dotnet restore ${{ inputs.context_path }}
      - name: Build
        run: dotnet build --no-restore ${{ inputs.context_path }}
      - name: Test
        run: dotnet test --no-build --verbosity normal ${{ inputs.context_path }}
