name: Build & Push Docker Image To JFROG

on:
  workflow_call:
    inputs:
      service_name:
        required: true
        type: string
      context_path:
        required: true
        type: string

permissions:
  contents: read

env:
  repository: bsiipoc.jfrog.io/default-docker/${{ inputs.service_name }}

jobs:
  build-push:
    runs-on: ubuntu-latest
    name: Service build and push
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to ECR
        uses: docker/login-action@v2.0.0
        with:
          registry: ${{ env.repository }}
          username: ${{ secrets.JFROG_DOCKER_USERNAME }}
          password: ${{ secrets.JFROG_DOCKER_PASSWORD }}
          logout: true

      - name: Replace branch name bad chars
        id: branch_name
        run: |
          if [ ${{ github.event_name }} == "pull_request" ]; then
            name=$( echo '${{ github.head_ref }}' | tr '/' '-' )
            echo "::set-output name=branch_name::$name"
          else
            name=$( echo '${{ github.ref_name }}' | tr '/' '-' )
            echo "::set-output name=branch_name::$name"
          fi

      - name: Docker build and push
        uses: docker/build-push-action@v3.2.0
        with:
          context: ${{ inputs.context_path }}
          push: ${{ github.event_name == 'push' }}  # Only push image to registry on "push" events.
          tags: 
            ${{ env.repository }}:${{ github.run_id }},
            ${{ env.repository }}:${{ steps.branch_name.outputs.branch_name }},
            ${{ env.repository }}:${{ github.sha }}
          file: ${{ inputs.dockerfile_path }} 
          build-args: |
            "BSII_NUGET_URL=${{ secrets.BSII_NUGET_URL }}"
            "BSII_NUGET_USER=${{ secrets.BSII_NUGET_USER }}"
            "BSII_NUGET_PASSWORD=${{ secrets.BSII_NUGET_PASSWORD }}"
