name: Pack & Push a Dotnet Nuget 

on:
  workflow_call:
    inputs:
      projects:
        default: "[]"
        required: true
        type: string
      version:
        required: true
        type: string
permissions:
  contents: read
  
jobs:
  pack-push:
    name: Push and Pack a Nuget
    runs-on: ubuntu-latest    
    environment: ${{ inputs.environment }}
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        path: ${{ fromJson(inputs.projects) }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: |
          dotnet nuget add source ${{ secrets.BSII_NUGET_URL }} -n ArtifactoryV2   -u ${{ secrets.BSII_NUGET_USER }} -p ${{ secrets.BSII_NUGET_PASSWORD }} --store-password-in-clear-text
          dotnet restore ${{ matrix.path }}
      - name: Pack
        run: |
          cd ${{ matrix.path  }}
          dotnet pack -c Release -o out -p:PackageVersion=${{ inputs.version }}
      - name: Push
        run: dotnet nuget push ${{ matrix.path  }}/out/*.nupkg -s ArtifactoryV2