name: Client Test

on:
  workflow_call:
    inputs:
      context_path:
        required: true
        type: string
      node_version:
        type: number
        default: 16

jobs:
  test:
    name: Client unit tests
    runs-on: ubuntu-latest
    continue-on-error: false
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version:  ${{ inputs.node_version }}
      - run: cd {{ inputs.context_path }}
      - run: npm install

      - uses: mansagroup/nrwl-nx-action@v3
        with:
          targets: lint, test, build
          workingDirectory: ${{ inputs.context_path }}

