name: Client Test

on:
  workflow_call:
    inputs:
      context_path:
        required: true
        type: string

jobs:
  test:
    name: Client unit tests
    runs-on: ubuntu-latest
    continue-on-error: false
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: mansagroup/nrwl-nx-action@v3
        with:
          targets: lint, test, build
          workingDirectory: ${{ inputs.context_path }}

