name: Client CI (NX)

on:
  workflow_call:
    inputs:
      context_path:
        required: true
        type: string
      node_version:
        type: number
        default: 16
      aws_ci_region:
        type: string
        default: "us-east-1"
jobs:
  nx-ci:
    name: Client CI (NX)
    runs-on: ubuntu-latest
    continue-on-error: false
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - uses: actions/setup-node@v3
        with:
          node-version:  ${{ inputs.node_version }}
          cache: 'npm'
          cache-dependency-path: ${{ inputs.context_path }}/package-lock.json
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
          aws-region: ${{ inputs.aws_ci_region }}

      - run: npm install
        working-directory: ${{ inputs.context_path }}

      - uses: mansagroup/nrwl-nx-action@v3
        with:
          targets: lint, test, build
          workingDirectory: ${{ inputs.context_path }}

