name: Python Test

on:
  workflow_call:
    inputs:
      unit-path:
        required: false
        type: string

  workflow_dispatch:
    inputs:
      test:
        description: "test"
        required: false
        default: "test"
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare repo
        uses: actions/checkout@master
      - name: Test
        uses: onichandame/python-test-action@master
        with:
          python-path: "./Python/bsii_cloud/storage_tests/s3-wrapper_test.py"
          deps_list: "requirement"
