name: Python Test

on:
  workflow_call:
    inputs:
      python-version:
        required: false
        type: string
        default: "3.9"
      requirements-path:
        required: false
        type: string
      setup-config-path:
        required: false
        type: string
      test-file-path:
        required: true
        type: string
      aws_ci_region:
        type: string
        default: "us-east-1"
      localstack-docker-compose:
        required: false
        type: string
        default: ""

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}

      - name: Configure AWS credentials "DEV"
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ARN_ROLE_OIDC_ADMINISTRATOR_DEV }}
          aws-region: ${{ inputs.aws_ci_region }}

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install dependencies
        if: "${{ inputs.requirements-path != '' }}"
        run: |
          python -m pip install --upgrade pip
          pip install -r ${{ inputs.requirements-path }}

      - name: Install dependencies of package
        if: "${{ inputs.setup-config-path != '' }}"
        run: |
          pip install ${{ inputs.setup-config-path }}

      - name: Setup LocalStack
        if: "${{ inputs.localstack-docker-compose != '' }}"
        run: |
          docker-compose -f ${{ inputs.localstack-docker-compose }} up -d
          pip install awscli-local
          while ! awslocal s3api list-buckets ; do
              echo "Waiting for LocalStack to be ready..."
              sleep 2
          done

      - name: Test with unittest
        run: python -m unittest ${{ inputs.test-file-path }}

      - name: Cleanup LocalStack
        if: "${{ inputs.localstack-docker-compose != '' }}"
        run: docker-compose -f ${{ inputs.localstack-docker-compose }} down
