name: Python Test

on:
  workflow_call:
    inputs:
      python-version:
        required: false
        type: string
        default: "3.9"
      requirements-path:
        required: false
        type: string
      setup-config-path:
        required: false
        type: string
      test-file-path:
        required: true
        type: string
      aws_ci_region:
        type: string
        default: "us-east-1"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_MODLECSI }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY_ID_MODLECSI }}
          aws-region: ${{ inputs.aws_ci_region }}

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install dependencies
        if: "${{ inputs.requirements-path != '' }}"
        run: |
          python -m pip install --upgrade pip
          pip install -r ${{ inputs.requirements-path }}

      - name: Install dependencies of package
        if: "${{ inputs.setup-config-path != '' }}"
        run: |
          pip install ${{ inputs.setup-config-path }}

      - name: Test with unittest
        run: |
          python -m unittest
          python -m unittest  ${{ inputs.test-file-path }}
