name: Python Test

on:
  workflow_call:
    inputs:
      unit-path:
        required: false
        type: string
      python-version:
        required: false
        type: string
        default: "3.9"

  workflow_dispatch:
    inputs:
      test:
        description: "test"
        required: false
        default: "test"
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}
      # You can test your matrix by printing the current Python version
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # pip install -r requirements.txt
      - name: Test with pytest
        run: |
          python -m unittest
          python -m unittest discover "./Python/bsii_cloud/bsii_cloud_storage/storage_tests/s3-wrapper_test.py"
