name: Python Test

on:
  workflow_call:
    inputs:
      python-version:
        required: false
        type: string
        default: "3.9"
      requirements-path:
        required: false
        type: string
      setup-config-path:
        required: false
        type: string
      test-path:
        required: false
        type: string
        default: "./Python/bsii_cloud/bsii_cloud_storage/storage_tests/s3-wrapper_test.py"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install dependencies
        if: "${{ github.event.inputs.requirements-path != '' }}"
        run: |
          python -m pip install --upgrade pip
          pip install -r ${{ inputs.requirements-path }}

      - name: Install dependencies of package
        if: "${{ github.event.inputs.setup-config-path != '' }}"
        run: |
          python -m pip install --upgrade pip
          cd ${{ inputs.setup-config-path }}
          pip install .

      - name: Test with unittest
        run: |
          python -m unittest
          python -m unittest  ${{ inputs.test-path }}
