name: Remove-argocd-applicationset

on:
  workflow_call:

env:
  aws_region:  us-east-1

permissions:
  contents: read

jobs:
  Remove-argocd-applicationset:
    if: github.event.ref_type == 'branch'
    runs-on: ubuntu-latest
    steps:
      - name: List environment variables 
        run: env

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
          aws-region: ${{ env.aws_region }}

      - name: Checkout argocd
        uses: actions/checkout@v3
        with:
          repository: brightsource-il/argocd
          token: ${{ secrets.REPO_ACCESS_ARGOCD }}

      - name: Delete branch from argocd repo
        run: |
          git branch origin -d ${{ github.event.ref }}
      
      - name: Delete applicationset from argocd namespace
        run: |
          kubectl delete appset ${{ github.event.repository.name }}-${{ github.event.ref }} -n argocd
      
      - name: Delete namespace from kubernetes
        run: |
          kubectl delete namespace ${{ github.event.repository.name }}-${{ github.event.ref }}