name: Remove-argocd-applicationset

on:
  workflow_call:

env:
  aws_region: us-east-1

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  Remove-argocd-applicationset:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials "DEV"
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ARN_ROLE_OIDC_ADMINISTRATOR_DEV }}
          aws-region: ${{ env.aws_region }}

      - name: Checkout argocd
        id: checkout_argocd_repo
        uses: actions/checkout@v3
        with:
          repository: brightsource-il/argocd
          ssh-key: ${{ secrets.ARGOCD_DEPLOY_KEY }}
          ref: dev
          fetch-depth: 0

      - name: Delete branch from argocd repo
        run: |
          git remote show origin | grep "Push  URL"  #Make sure we are in argocd repo
          branch_without_slashes=$(echo "${{ github.head_ref }}" | sed 's/\//-/g')
          git ls-remote --exit-code --heads origin ${{ github.event.repository.name }}-$branch_without_slashes
          EXIT_CODE=$?

          if [[ $EXIT_CODE == '0' ]]; then
            echo "Deleting argocd branch '${{ github.event.repository.name }}-$branch_without_slashes'."
            git push origin --delete ${{ github.event.repository.name }}-$branch_without_slashes;
          elif [[ $EXIT_CODE == '2' ]]; then
            echo "Git branch '${{ github.event.repository.name }}-$branch_without_slashes' does not exist in the remote repository."
          fi

      - name: Delete applicationset from argocd namespace
        run: |
          aws eks --region ${{ env.aws_region }} update-kubeconfig --name dev-brightsource
          branch_without_slashes=$(echo "${{ github.head_ref }}" | sed 's/\//-/g')
          if kubectl get appset ${{ github.event.repository.name }}-$branch_without_slashes -n argocd  &> /dev/null; 
          then
            kubectl delete appset ${{ github.event.repository.name }}-$branch_without_slashes -n argocd; 
          fi

      - name: Delete namespace from kubernetes
        run: |
          branch_without_slashes=$(echo "${{ github.head_ref }}" | sed 's/\//-/g')
          if kubectl get namespace ${{ github.event.repository.name }}-$branch_without_slashes &> /dev/null; 
          then 
            kubectl delete namespace ${{ github.event.repository.name }}-$branch_without_slashes; 
          fi
